require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.0.1
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - db/migrate/*

RSpec/ImplicitExpect:
  EnforcedStyle: should
